"""
Model Fit Visualization Script

This script contains visualization code moved from dimensional-analysis.ipynb.
It creates various plots to visualize IRT model performance and ability estimates.

REQUIRED FILES TO START VISUALIZATION:
- ../data/resmat.pkl                    # Response matrix data
- ../data/mirt_model_k{k}_rep{r}.pt     # Trained MIRT models for different K and repetitions
- ../output/standard_errors_k{k}.npz    # Standard error arrays (generated by dimensional analysis)
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import sys
import torch
from load_params import load_and_rotate

# Add parent directory to path for style imports
sys.path.append('..') 
import style

# Configuration
DATA_DIR = "../data"
OUTPUT_DIR = "../output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

def load_response_matrix():
    """Load the response matrix from pickle file."""
    return pd.read_pickle("../data/resmat.pkl")

def create_1d_ability_plot(k=1, r=93):
    """
    Create ability plot for 1-dimensional IRT model.
    
    Args:
        k (int): Number of dimensions (should be 1)
        r (int): Repetition number to use
    """
    print(f"Creating 1D ability plot for K={k}, repetition={r}")
    
    # Load data
    resmat = load_response_matrix()
    theta_se = np.load(f"../output/standard_errors_k{k}.npz")['theta_se']
    # For 1D case, rotation has no effect, so we can use None
    theta, a, b = load_and_rotate(os.path.join(DATA_DIR, f"mirt_model_k{k}_rep{r}.pt"), rotation=None)

    # Prepare data
    data_for_df = {
        'ability_dim1': theta[:, 0],
        'se_dim1': theta_se[:, 0]
    }
    theta_df = pd.DataFrame(data_for_df, index=resmat.index)
    
    # Create plot
    df_sorted = theta_df.sort_values('ability_dim1', ascending=False)
    labels = df_sorted.index
    ability1 = df_sorted['ability_dim1']
    ci1 = df_sorted['se_dim1']
    x = np.arange(len(labels))
    width = 0.35

    fig, ax = plt.subplots(figsize=(90, 10))
    rects1 = ax.bar(x - width/2, ability1, width, label='Dimension 1', 
                    yerr=ci1, capsize=4, color='skyblue')

    ax.set_ylabel('Estimated Ability (Theta)', fontsize=14)
    ax.set_title('IRT Ability Estimates', fontsize=16)
    ax.set_xticks(x)
    ax.set_xticklabels(labels)
    ax.legend()
    plt.xticks(rotation=90)
    ax.axhline(0, color='grey', linewidth=0.8)
    fig.tight_layout()

    plt.savefig(f'../output/dual_dimension_ability_plot_k{k}.pdf', bbox_inches='tight')
    plt.show()
    
    return theta_df

def create_2d_ability_plot(k=2, r=87):
    """
    Create ability plot for 2-dimensional MIRT model.
    
    Args:
        k (int): Number of dimensions (should be 2)
        r (int): Repetition number to use
    """
    print(f"Creating 2D ability plot for K={k}, repetition={r}")
    
    # Load data
    resmat = load_response_matrix()
    theta_se = np.load(f"../output/standard_errors_k{k}.npz")['theta_se']
    # Use oblimin rotation by default (can omit rotation parameter or specify explicitly)
    theta, a, b = load_and_rotate(os.path.join(DATA_DIR, f"mirt_model_k{k}_rep{r}.pt"))

    # Prepare data
    data_for_df = {
        'ability_dim1': theta[:, 0],
        'se_dim1': theta_se[:, 0],
        'ability_dim2': theta[:, 1],
        'se_dim2': theta_se[:, 1]
    }
    theta_df = pd.DataFrame(data_for_df, index=resmat.index)
    
    # Create plot
    df_sorted = theta_df.sort_values('ability_dim1', ascending=False)
    labels = df_sorted.index
    ability1 = df_sorted['ability_dim1']
    ability2 = df_sorted['ability_dim2']
    ci1 = df_sorted['se_dim1']
    ci2 = df_sorted['se_dim2']
    x = np.arange(len(labels))
    width = 0.35

    fig, ax = plt.subplots(figsize=(90, 10))
    rects1 = ax.bar(x - width/2, ability1, width, label='Dimension 1', 
                    yerr=ci1, capsize=4, color='skyblue')
    rects2 = ax.bar(x + width/2, ability2, width, label='Dimension 2', 
                    yerr=ci2, capsize=4, color='salmon')

    ax.set_ylabel('Estimated Ability (Theta)', fontsize=14)
    ax.set_title('MIRT Ability Estimates', fontsize=16)
    ax.set_xticks(x)
    ax.set_xticklabels(labels)
    ax.legend()
    plt.xticks(rotation=90)
    ax.axhline(0, color='grey', linewidth=0.8)
    fig.tight_layout()

    plt.savefig(f'../output/dual_dimension_ability_plot_k{k}.pdf', bbox_inches='tight')
    plt.show()
    
    return theta_df

def create_baseline_accuracy_plot(fill_nan=True):
    """
    Create baseline accuracy plot using raw scores.
    
    Args:
        fill_nan (bool): If True, fill NaN values with 0. If False, ignore NaN values.
    """
    print(f"Creating baseline accuracy plot (fill_nan={fill_nan})")
    
    # Load data
    resmat = load_response_matrix()
    
    # Calculate baseline accuracy
    if fill_nan:
        average_score_baseline = resmat.fillna(0).mean(axis=1)
        title_suffix = " (NaN filled with 0)"
        filename_suffix = "_nan_filled"
    else:
        average_score_baseline = resmat.mean(axis=1)  # Ignores NaN
        title_suffix = " (NaN ignored)"
        filename_suffix = "_nan_ignored"
    
    # Create DataFrame
    baseline_df = pd.DataFrame({
        'raw_accuracy': average_score_baseline
    }, index=resmat.index).sort_values(by='raw_accuracy', ascending=False)
    
    print("--- Top 10 Models by Raw Accuracy ---")
    print(baseline_df.head(10))
    
    # Create plot
    df_sorted = baseline_df.sort_values('raw_accuracy', ascending=False)
    labels = df_sorted.index
    ability1 = df_sorted['raw_accuracy']
    x = np.arange(len(labels))
    width = 0.35

    fig, ax = plt.subplots(figsize=(90, 10))
    rects1 = ax.bar(x - width/2, ability1, width, label='Average Accuracy', 
                    capsize=4, color='skyblue')

    ax.set_ylabel('Accuracy', fontsize=14)
    ax.set_title(f'Average Accuracy by Model{title_suffix}', fontsize=16)
    ax.set_xticks(x)
    ax.set_xticklabels(labels)
    ax.legend()
    plt.xticks(rotation=90)
    ax.axhline(0, color='grey', linewidth=0.8)
    fig.tight_layout()

    plt.savefig(f'../output/baseline_accuracy_plot{filename_suffix}.pdf', bbox_inches='tight')
    plt.show()
    
    return baseline_df

def compare_models_statistically(theta_df, model_a_name, model_b_name, dimension='ability_dim1'):
    """
    Compare two models statistically using z-test.
    
    Args:
        theta_df (pd.DataFrame): DataFrame with ability estimates and standard errors
        model_a_name (str): Name of first model
        model_b_name (str): Name of second model
        dimension (str): Which dimension to compare
    """
    print(f"Comparing {model_a_name} and {model_b_name} on {dimension}")
    
    # Get the values
    se_col = dimension.replace('ability', 'se')
    ability_a = theta_df.loc[model_a_name, dimension]
    se_a = theta_df.loc[model_a_name, se_col]
    ability_b = theta_df.loc[model_b_name, dimension]
    se_b = theta_df.loc[model_b_name, se_col]

    # Calculate the z-statistic
    se_difference = np.sqrt(se_a**2 + se_b**2)
    z_statistic = (ability_a - ability_b) / se_difference

    # Print results
    print(f"  Ability Difference: {ability_a - ability_b:.4f}")
    print(f"  Z-Statistic: {z_statistic:.4f}")

    if abs(z_statistic) > 1.96:
        print("  Conclusion: The difference is statistically significant (p < 0.05).")
    else:
        print("  Conclusion: The difference is NOT statistically significant.")
    
    return z_statistic

def create_performance_tiers(df, ability_col, se_col, alpha=0.05):
    """
    Groups models into performance tiers based on statistical significance.

    Args:
        df (pd.DataFrame): DataFrame containing model performance data.
        ability_col (str): The name of the column with ability scores (theta).
        se_col (str): The name of the column with standard errors.
        alpha (float): The significance level for the z-test (e.g., 0.05 for 95% confidence).

    Returns:
        pd.DataFrame: The original DataFrame with an added 'tier' column.
    """
    from scipy.stats import norm
    
    print(f"Creating performance tiers based on {ability_col} with alpha={alpha}")
    
    # Sort models by ability in descending order
    df_sorted = df.sort_values(by=ability_col, ascending=False).copy()

    if df_sorted.empty:
        return df_sorted
    
    # Calculate the critical z-value from the significance level
    critical_z = norm.ppf(1 - alpha / 2)  # e.g., for alpha=0.05, this is ~1.96
    
    tiers = [0] * len(df_sorted)
    current_tier = 1
    anchor_idx = 0  # The index of the top model in the current tier
    
    # The first model is always in Tier 1
    tiers[0] = current_tier

    # Iterate through models to assign tiers
    for i in range(1, len(df_sorted)):
        # Get anchor model's data (top of the current tier)
        anchor_ability = df_sorted.iloc[anchor_idx][ability_col]
        anchor_se = df_sorted.iloc[anchor_idx][se_col]

        # Get current model's data
        current_ability = df_sorted.iloc[i][ability_col]
        current_se = df_sorted.iloc[i][se_col]
        
        # Perform the Z-test against the anchor
        se_difference = np.sqrt(anchor_se**2 + current_se**2)
        # Avoid division by zero if SEs are zero
        if se_difference > 0:
            z_statistic = (anchor_ability - current_ability) / se_difference
        else:
            z_statistic = np.inf if anchor_ability != current_ability else 0
        
        # Assign to a tier
        if abs(z_statistic) <= critical_z:
            # Difference is NOT significant, so it's in the same tier
            tiers[i] = current_tier
        else:
            # Difference IS significant, so it starts a new tier
            current_tier += 1
            tiers[i] = current_tier
            # This model is now the anchor for the new tier
            anchor_idx = i
            
    df_sorted['tier'] = tiers
    return df_sorted

def main():
    """Main function to run all visualizations."""
    print("=== Model Fit Visualization Script ===")
    print("This script creates various plots to visualize IRT model performance.")
    print()
    
    # Check if required files exist
    required_files = [
        "../data/resmat.pkl",
        "../output/standard_errors_k1.npz",
        "../output/standard_errors_k2.npz"
    ]
    
    missing_files = []
    for file_path in required_files:
        if not os.path.exists(file_path):
            missing_files.append(file_path)
    
    if missing_files:
        print("WARNING: The following required files are missing:")
        for file_path in missing_files:
            print(f"  - {file_path}")
        print("Please ensure these files exist before running the visualizations.")
        print()
    
    try:
        # Create baseline accuracy plots
        print("1. Creating baseline accuracy plots...")
        baseline_df_nan_ignored = create_baseline_accuracy_plot(fill_nan=False)
        baseline_df_nan_filled = create_baseline_accuracy_plot(fill_nan=True)
        
        # Create 1D ability plot
        print("\n2. Creating 1D IRT ability plot...")
        theta_df_1d = create_1d_ability_plot(k=1, r=93)
        
        # Create 2D ability plot
        print("\n3. Creating 2D MIRT ability plot...")
        theta_df_2d = create_2d_ability_plot(k=2, r=87)
        
        # Example statistical comparison
        print("\n4. Example statistical comparison...")
        model_a = 'anthropic/claude-3-haiku-20240307'  # Update with actual model names
        model_b = 'openai/gpt-3.5-turbo-1106'  # Update with actual model names
        
        if model_a in theta_df_2d.index and model_b in theta_df_2d.index:
            compare_models_statistically(theta_df_2d, model_a, model_b, 'ability_dim1')
        else:
            print(f"  Models {model_a} or {model_b} not found in data. Skipping comparison.")
        
        # Create performance tiers
        print("\n5. Creating performance tiers...")
        tiered_results = create_performance_tiers(
            df=theta_df_2d, 
            ability_col='ability_dim1', 
            se_col='se_dim1'
        )
        
        print("\n--- Models with Assigned Performance Tiers ---")
        print(tiered_results[['ability_dim1', 'se_dim1', 'tier']].head(10))
        
        print("\n--- Final Tiers Grouped for Clarity ---")
        for tier_num, group in tiered_results.groupby('tier'):
            print(f"Tier {tier_num}: {list(group.index)}")
        
        print("\n=== All visualizations completed successfully! ===")
        
    except Exception as e:
        print(f"ERROR: {str(e)}")
        print("Please ensure all required files are present and dependencies are installed.")

if __name__ == "__main__":
    main()
